const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim shirt',
            slug: 'nike-slim-shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quailty shirt',
        },
        {
            _id: '2',
            name: 'Nike Slim pants',
            slug: 'nike-slim-pants',
            category: 'Pants',
            image: '/images/p3.jpg',
            price: 25,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.4,
            numReviews: 14,
            description: 'high quailty pants',
        },
        {
            _id: '3',
            name: 'Adidas Fit pants',
            slug: 'adidas-slim-pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.0,
            numReviews: 22,
            description: 'high quailty pants',
        },
    ],
};

export default data;